#!/usr/bin/env python3
"""Basic summary analysis for collected GitHub repository data."""

from __future__ import annotations

import argparse
import csv
from collections import Counter
from pathlib import Path
from typing import Optional


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Summarize repositories.csv.")
    parser.add_argument(
        "csv_path",
        nargs="?",
        default="data/repositories.csv",
        help="Path to the CSV generated by collector.py.",
    )
    return parser.parse_args()


def as_int(value: Optional[str]) -> int:
    if value in {None, ""}:
        return 0
    return int(value)


def main() -> int:
    args = parse_args()
    path = Path(args.csv_path)

    with path.open("r", encoding="utf-8", newline="") as csv_file:
        rows = list(csv.DictReader(csv_file))

    if not rows:
        print("No rows found.")
        return 0

    languages = Counter(row["language"] or "Unknown" for row in rows)
    owners = Counter(row["owner_type"] or "Unknown" for row in rows)
    total_stars = sum(as_int(row["stargazers_count"]) for row in rows)
    total_forks = sum(as_int(row["forks_count"]) for row in rows)
    top_by_stars = sorted(rows, key=lambda row: as_int(row["stargazers_count"]), reverse=True)[:10]

    print(f"Repositories analyzed: {len(rows)}")
    print(f"Average stars: {total_stars / len(rows):,.1f}")
    print(f"Average forks: {total_forks / len(rows):,.1f}")

    print("\nTop languages:")
    for language, count in languages.most_common(10):
        print(f"  {language}: {count}")

    print("\nOwner types:")
    for owner_type, count in owners.most_common():
        print(f"  {owner_type}: {count}")

    print("\nTop repositories by stars:")
    for repo in top_by_stars:
        print(
            f"  {repo['full_name']}: {int(repo['stargazers_count']):,} stars, "
            f"{int(repo['forks_count']):,} forks"
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
